In [5]:
import pandas as pd

In [6]:
df = pd.read_excel('./TODOS_USUARIOS_POR_TODOS_LOS_ESTADOS_21_septiembre_2023.xlsx')

In [70]:
df_clear = df.rename(columns={
    'NOMBRES/ RAZON SOCIAL':'name',
    'ABONADO': 'n_contrato',
    'ESTADO': 'estado', 
    'TIPO DE PERSONA': 'tipo_persona',  
    'Nº DOCUMENTO': 'n_documento', 
    'TIPO DE VIVIENDA': 'tipo_vivienda', 
    'Municipio': 'municipio', 
    'Barrio':'barrio', 
    'Direccion':'direccion',
    'NUM-CASA': 'n_casa', 
    'REF DIRECCION Y ESTRATO':'estrato', 
    'TEL 1':'tel1', 
    'TEL 2': 'tel2', 
    'TEL 3': 'tel3',
    'FECHA NAC.':'fecha_cumple',
    'E-MAIL': 'email',
    'OS INSTAL':'os_instal', 
    'F INSTAL':'fecha_instal', 
    'SERVICIO INTERNET': 'servicio',
    'DEUDA': 'deuda',
    'DET DEUDA': 'detalle_deuda', 
    'CAJA NAP ': 'caja_nap', 
    'FECHA ULTIMO CORTE':'fecha_ultimo_corte',
    'PAGO ULT MESES': 'ultimo_mes_pago',
    'TARIFA INTERNET': 'plan',
    'PRECIO TARIFA INTERNET': 'precio_tarifa',
    'OS INST INTER': 'os_instal_interno', 
    'FECHA INST': 'fecha_instalacion',
    'OS CORTE INTER':'os_corte_interno',
    'FECHA CORTE INST': 'os_corte_instal',
    'FECHA ULT PAG': 'ultimo_pago', 
    'FEC. ING. CONTRATO': 'inicio_contrato',
    'VENDEDOR INSTALACION': 'vendedor',
    'MESES ADEUDADO':  'mes_adeudado', 
    'TIPO DE DOCUMENTO': 'tipo_documento',
    'SEXO': 'sexo',
    'ESTADO CUENTA POR CORREO' : 'estado_cp_correo',
    'CORREO ENVIO ESTADO CUENTA' : 'correo',
    'REP. CENTRAL RIESGO': 'reporte_c_riesgo',
    'MARCA ONU ':'marca_onu' , 
    'MAC O SERIAL ONU ':'mac'
    })
df_clear.columns

Index(['n_contrato', 'name', 'estado', 'tipo_persona', 'n_documento',
       'tipo_vivienda', 'municipio', 'barrio', 'direccion', 'n_casa',
       'estrato', 'tel1', 'tel2', 'tel3', 'fecha_cumple', 'email', 'os_instal',
       'fecha_instal', 'servicio', 'deuda', 'detalle_deuda', 'caja_nap',
       'fecha_ultimo_corte', 'ultimo_mes_pago', 'plan', 'precio_tarifa',
       'os_instal_interno', 'fecha_instalacion', 'os_corte_interno',
       'os_corte_instal', 'ultimo_pago', 'inicio_contrato', 'vendedor',
       'mes_adeudado', 'tipo_documento', 'sexo', 'estado_cp_correo', 'correo',
       'reporte_c_riesgo', 'marca_onu', 'mac'],
      dtype='object')

In [71]:
df_user = df_clear[[
    'name',
    'sexo',
    'tipo_persona',
    'tipo_documento',
    'fecha_cumple',
    'n_documento', 
    'email',
    'n_contrato'
    ]]
df_user

,name,sexo,tipo_persona,tipo_documento,fecha_cumple,n_documento,email,n_contrato
0,"OCAMPO DURAN, ALVARO",MASCULINO,P. NATURAL,CC,1958-12-15,16613915,AOCAMPODURAN@GMAIL.COM,1
1,"BOTERO LONDOÑO, YENY CLEMENTINA",FEMENINO,P. NATURAL,CC,1995-10-25,1010016237,YENYBOTERO7@GMAIL.COM,2
2,"AGUILERA PIÑEROS, ZENON",MASCULINO,P. NATURAL,CC,1971-08-28,3276139,ZENON.AGUILERA@HOTMAIL.COM,3
3,"MORENO PIÑEROS, NELCY",FEMENINO,P. NATURAL,CC,1956-06-04,21238479,MYMOPI.MM@GMAIL.COM,4
4,"ESPEJO SANCHEZ, GLORIA IRENE",FEMENINO,P. NATURAL,CC,1987-10-07,1119887083,GLO_IRE_ES@HOTMAIL.COM,5
...,...,...,...,...,...,...,...,...
627,"AMAYA DUARTE, LLEHINSON FIDEL",MASCULINO,P. NATURAL,CC,1990-03-19,1119888667,AMAYAJEISSOB@GMAIL.COM,635
628,"PARRADO GAONA, HEIDY YHUBISA",FEMENINO,P. NATURAL,CC,2003-04-20,1006859153,PARRADOHEIDY@ICLOUD.COM,636
629,"RODRIGUEZ MONROY, GLORIA MIRIAM",FEMENINO,P. NATURAL,CC,1960-01-24,51690062,RODRIGUEMYRIAM708@GMAIL.COM,637
630,"LINARES SALCEDO, MARIA ANGELICA",FEMENINO,P. NATURAL,CC,1996-09-29,1122653154,LINARESANGELICA29@GMAIL.COM,638
631,"MORERA MENDEZ, ELINTON AMADEO",MASCULINO,P. NATURAL,CC,1993-06-11,1119890604,CLINTONMORERA25@GMAIL.COM,639

In [72]:

df_contract = df_clear[[
    'n_contrato',
    'estado', 
    'tipo_vivienda', 
    'municipio', 
    'barrio', 
    'direccion',
    'n_casa', 
    'estrato', 
    'tel1', 
    'tel2', 
    'tel3',
    'os_instal', 
    'mac', 
    'servicio',
    'deuda', 
    'detalle_deuda', 
    'caja_nap', 
    'fecha_ultimo_corte',
    'ultimo_mes_pago', 
    'plan', 
    'precio_tarifa',
    'os_instal', 
    'fecha_instal', 
    'os_corte_interno', 
    'fecha_instalacion',
    'ultimo_pago', 
    'inicio_contrato', 
    'vendedor',
    'mes_adeudado', 
    'estado_cp_correo',
    'correo',
    'reporte_c_riesgo', 
    'marca_onu', 
    'mac',
    'n_documento', 
    ]]
df_contract.head(5)

,n_contrato,estado,tipo_vivienda,municipio,barrio,direccion,n_casa,estrato,tel1,tel2,...,ultimo_pago,inicio_contrato,vendedor,mes_adeudado,estado_cp_correo,correo,reporte_c_riesgo,marca_onu,mac,n_documento
0,1,ACTIVO,CASA PROPIA,CUMARAL,GUACAVIA,FINCA,.KILIAWIRINA,ESTRATO 2,-/3138713550/3202319109/3153344789,3202319109,...,2023-09-06,2021-03-09,"OFICINA OFICINA, OFICINA RESERVADO",0,NO,NaN,NO,NaN,NaN,16613915
1,2,RETIRADO,CASA ALQUILADA,CUMARAL,MONSERRATE,CARRERA 16,.10-12 APT 2,USUARIO SOLICITA TRASLADO PARA EL BARRIO MONSE...,-/3172456372/3143034687/3144387361,3143034687,...,2022-08-22,2021-03-10,"OFICINA OFICINA, OFICINA RESERVADO",0,NO,NaN,NO,NaN,NaN,1010016237
2,3,RETIRADO,CASA PROPIA,CUMARAL,GUACAVIA,CALLE 7,.5 A 33,ESTRATO 1,-/3507049240/3133075484/3102253829,3133075484,...,2023-07-11,2021-03-10,"VIUCHE GUEVARA, ANGIE NATALIA",0,NO,NaN,NO,NaN,NaN,3276139
3,4,ACTIVO,CASA PROPIA,CUMARAL,GUACAVIA,CALLE 7,.6-251,EL ENSUEÑO ESTRATO 1,-/3153877158/3204334018/3156486193,3204334018,...,2023-09-06,2021-03-11,"GUEVARA TAPIERO, YEIMI",0,NO,NaN,NO,NaN,NaN,21238479
4,5,ACTIVO,CASA ALQUILADA,CUMARAL,GUACAVIA,GUACAVIA,.IN TITUCION AGRICOLA,EFECTY ESTRATO 2,-/3202901730/3157972599/3219653231,3157972599,...,2023-08-28,2021-03-11,"GUEVARA TAPIERO, YEIMI",0,NO,NaN,NO,NaN,NaN,1119887083

In [1]:
df_users.to_json(path_or_buf='users' ,orient='records')
df_users

NameError: name 'df_users' is not defined